services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Affankhan0966
      POSTGRES_DB: rag_chatbot
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
